Repository unhindered-ec/unhindered-ec, pull requests merged in 2024-07, with the labels that each got.

#226 Improved editor configs
  .helix/languages.toml
  .vscode/settings.json
Labels: E-easy, C-small, P-medium, S-waiting-on-review, C-improvement

#224 Add benchmark for evaluating floating point Push program
  Cargo.lock
  packages/push/Cargo.toml
  packages/push/benches/regression-evaluation.rs
Labels: A-push-interpreter, A-testing, E-easy, P-low, C-perf-regression

#229 Actually use nightly in vscode for clippy lints.
  .vscode/settings.json
Labels: C-bug, E-easy, C-small, P-high, S-waiting-on-review

#228 Lint reasons
  Cargo.lock
  Cargo.toml
  packages/ec-core/Cargo.toml
  packages/ec-core/src/distributions/collection.rs
  packages/ec-core/src/distributions/one_of_macro.rs
  packages/ec-core/src/distributions/wrappers/owned.rs
  packages/ec-core/src/individual/ec.rs
  packages/ec-core/src/operator/composable/repeat_with.rs
  packages/ec-core/src/operator/composable/then.rs
  packages/ec-core/src/operator/selector/best.rs
  packages/ec-core/src/operator/selector/lexicase.rs
  packages/ec-core/src/population.rs
  packages/ec-linear/Cargo.toml
  packages/ec-linear/examples/count_ones/main.rs
  packages/ec-linear/examples/hiff/main.rs
  packages/ec-linear/src/mutator/umad.rs
  packages/ec-linear/src/mutator/with_one_over_length.rs
  packages/ec-linear/src/mutator/with_rate.rs
  packages/push/Cargo.toml
  packages/push/benches/regression-evaluation.rs
  packages/push/examples/complex_regression/main.rs
  packages/push/examples/simple_regression/main.rs
  packages/push/examples/smallest/main.rs
  packages/push/src/genome/plushy.rs
  packages/push/src/instruction/bool.rs
  packages/push/src/instruction/exec/dup_block.rs
  packages/push/src/instruction/exec/ifelse.rs
  packages/push/src/instruction/exec/noop.rs
  packages/push/src/instruction/exec/unless.rs
  packages/push/src/instruction/exec/when.rs
  packages/push/src/instruction/float.rs
  packages/push/src/instruction/int/mod.rs
  packages/push/src/instruction/int/negate.rs
  packages/push/src/instruction/variable_name.rs
  packages/push/src/push_vm/program.rs
  packages/push/src/push_vm/push_state.rs
  packages/push/src/push_vm/stack.rs
  packages/push/tests/cases.rs
  packages/push/tests/float.rs
  packages/push/tests/int.rs
Labels: A-clippy-lints, C-cleanup, E-medium, I-prioritize, P-high, S-waiting-on-review

#232 Rename `CollectionGenerator` to just `Generator`
  .vscode/settings.json
  packages/ec-core/src/distributions/collection.rs
  packages/ec-linear/src/genome/bitstring.rs
  packages/push/src/genome/plushy.rs
Labels: A-clippy-lints, C-cleanup, E-easy, P-low, A-ec-core

#233 Convert `if-else` chain to `match` in lexicase selection
  Cargo.lock
  packages/ec-core/Cargo.toml
  packages/ec-core/proptest-regressions/operator/selector/lexicase.txt
  packages/ec-core/src/individual/ec.rs
  packages/ec-core/src/operator/selector/lexicase.rs
  packages/push/Cargo.toml
  packages/push/src/push_vm/stack.rs
Labels: E-easy, P-low, C-improvement

#237 Ensure that tournament sizes are positive
  Cargo.lock
  Cargo.toml
  packages/ec-core/proptest-regressions/operator/selector/tournament.txt
  packages/ec-core/src/operator/selector/tournament.rs
  packages/ec-linear/examples/count_ones/main.rs
  packages/ec-linear/examples/hiff/main.rs
  packages/push/examples/simple_regression/main.rs
Labels: A-selectors, E-easy, E-needs-test, C-small, P-medium, relnotes, C-improvement
