Repository unhindered-ec/unhindered-ec, pull requests merged in 2024-05, with the labels that each got.

#192 Update tag names
  scripts/issue_creator.nu
Labels: C-bug, disposition-merge, E-easy, C-small, P-medium

#194 Set the labels used explicitly for dependabot
  .github/dependabot.yml
Labels: C-bug, A-ci, disposition-merge, E-easy, C-small, P-low, S-waiting-on-review

#204 Benchmark `TestResult`
  Cargo.lock
  Cargo.toml
  packages/ec-core/Cargo.toml
  packages/ec-core/benches/test_results.rs
Labels: A-testing, C-optimization, E-easy, P-medium
